In [1]:
import pandas as pd
import numpy as np
from IPython.display import display
df = pd.read_csv("dataset.csv")

display(df)


Applicants Location preference 1 Location preference 2  \
0        Aarav            Plattsburg             Green Bay   
1        Aaron            Palm Coast             Pensacola   
2       Abdiel                Mobile           Panama City   
3       Abdoul            Shreveport                  York   
4    Abdoulaye          Fayetteville             Paragould   
..         ...                   ...                   ...   
495   Yehoshua                 Salem              Goodland   
496     Yehuda             Green Bay              Victoria   
497      Yidel            Dodge City             Lakeville   
498    Yisrael            Fort Wayne             Goldsboro   
499        Zev                Pierre          Philadelphia   

    Location preference 3 Location preference 4 Location preference 5  
0                  Joplin          Jacksonville               Sanford  
1                  Toledo               Lansing               Raleigh  
2           Atlantic City      Washington, D.C.               Chicago  
3                 Baytown            San Marcos          Apalachicola  
4             Springfield                  Gary           Springfield  
..                    ...                   ...                   ...  
495              Cheyenne              Waukegan             Oak Ridge  
496            Belleville           Panama City             Rock Hill  
497            Pittsburgh              Van Horn             Brookings  
498                Wausau            Eagle Pass              Appleton  
499            New Albany              Escanaba                Marion  

[500 rows x 6 columns]

In [2]:
applicants = list(df['Applicants'])
applicants.sort()

locations = set()
locations.update(set(df['Location preference 1']))
locations.update(set(df['Location preference 2']))
locations.update(set(df['Location preference 3']))
locations.update(set(df['Location preference 4']))
locations.update(set(df['Location preference 5']))
locations = list(locations)
locations.sort()

for i in range(len(applicants)):
    df["Applicants"] = df["Applicants"].replace(to_replace = applicants[i] ,value = i)

for i in range(len(locations)):
    df["Location preference 1"] = df["Location preference 1"].replace(to_replace = locations[i] ,value = i)
    df["Location preference 2"] = df["Location preference 2"].replace(to_replace = locations[i] ,value = i)
    df["Location preference 3"] = df["Location preference 3"].replace(to_replace = locations[i] ,value = i)
    df["Location preference 4"] = df["Location preference 4"].replace(to_replace = locations[i] ,value = i)
    df["Location preference 5"] = df["Location preference 5"].replace(to_replace = locations[i] ,value = i)
display(df)

Applicants  Location preference 1  Location preference 2  \
0             0                    340                    172   
1             1                    324                    331   
2             2                    282                    325   
3             3                    385                    465   
4             4                    143                    326   
..          ...                    ...                    ...   
495         495                    367                    166   
496         496                    172                    434   
497         497                    116                    233   
498         498                    151                    165   
499         499                    336                    335   

     Location preference 3  Location preference 4  Location preference 5  
0                      214                    206                    373  
1                      416                    236                    354  
2                       25                    438                     80  
3                       38                    372                     19  
4                      395                    163                    395  
..                     ...                    ...                    ...  
495                     79                    443                    312  
496                     44                    325                    361  
497                    338                    430                     59  
498                    445                    125                     20  
499                    298                    137                    265  

[500 rows x 6 columns]

In [3]:
data = df.to_numpy()
graph = np.zeros((len(applicants),len(locations)),dtype=int)
print("Converted to numpy array")
print(data)

for i in range(len(applicants)):
    for j in range(1,6):
        graph[i,data[i,j]] = 1
print("\nConverted to graph")        
print(graph)

Converted to numpy array
[[  0 340 172 214 206 373]
 [  1 324 331 416 236 354]
 [  2 282 325  25 438  80]
 ...
 [497 116 233 338 430  59]
 [498 151 165 445 125  20]
 [499 336 335 298 137 265]]

Converted to graph
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [4]:
class Graph:
    def __init__(self,graph):

        # residual graph
        self.graph = graph
        self.applicants = len(graph[:,0])
        self.locations = len(graph[0,:])

    # A DFS based recursive function
    # that returns true if a matching
    # for vertex u is possible
    def searchMatch(self, u, matchings, visited):

        # Try every location one by one
        for v in range(self.locations):

            # If applicant u is interested
            # in location v and v is not visited
            if self.graph[u,v] and visited[v] == False:

                # Mark v as visited
                visited[v] = True

                '''If location 'v' is not assigned to
                an applicant OR previously assigned
                applicant for location v (which is matchings[v])
                has an alternate location available.
                Since v is marked as visited in the
                above line, matchings[v] in the following
                recursive call will not get location 'v' again'''
                if matchings[v] == -1 or self.searchMatch(matchings[v],matchings, visited):
                    matchings[v] = u
                    return True
        return False

    # Returns maximum number of matching
    def maximumBipartiteMatching(self):
        '''An array to keep track of the
        applicants assigned to locations.
        The value of matchings[i] is the
        applicant number assigned to location i,
        the value -1 indicates nobody is assigned.'''
        matchings = [-1] * self.locations
        
        # Count of locations assigned to applicants
        result = 0
        for i in range(self.applicants):

            # Mark all locations as not visited for next applicant.
            visited = [False] * self.locations

            # Find if the applicant 'u' can get a location
            if self.searchMatch(i, matchings, visited):
                result += 1
        return (matchings,result)

g = Graph(graph)
(matchings,result) = g.maximumBipartiteMatching()



In [5]:
data = {'Applicant': matchings, 'Location': list(range(len(matchings)))}

dfMatchings = pd.DataFrame(data)
for i in dfMatchings['Applicant']:
    dfMatchings["Applicant"] = dfMatchings["Applicant"].replace(to_replace = i ,value = applicants[i])
for i in dfMatchings['Location']:
    dfMatchings["Location"] = dfMatchings["Location"].replace(to_replace = i ,value = locations[i])
#dfMatchings = dfMatchings.sort_values(by = 'Applicant')

print ("Maximum number of applicants that that got preferred location:", result)
display(dfMatchings)

Maximum number of applicants that that got preferred location: 468


Applicant    Location
0        Dylan    Aberdeen
1       Devora     Abilene
2       Amanda       Aiken
3        Bryce       Akron
4     Jonathan      Albany
..         ...         ...
463    Giselle   Worcester
464  Guadalupe     Yankton
465     Jazmin        York
466     Daniel  Youngstown
467     Amelie  Zanesville

[468 rows x 2 columns]